---
linux:
  children:
    nginx:
      hosts:
        vm-1:
          ansible_host: 89.169.159.104
        vm-2:
          ansible_host: 158.160.35.129
        vm-3:
          ansible_host: 158.160.62.43
  vars:
    ansible_user: s21309416
    ansible_ssh_private_key_file: /home/s21309416/.ssh/id_ed25519
    ansible_become: true
    ansible_become_method: sudo
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    connection_protocol: ssh
